namespace: acrpull
image: registry/image:tag
replicas: 2
nodeSelector: {}
tolerations: []
affinity: {}
ttlRotationFraction: 0.5
kubeAPIQPS: 20
kubeAPIBurst: 30
allowedACRServerSuffixes:
  - azurecr.io
