version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
