apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "controller-token-request-policy-binding"
  labels:
    app.kubernetes.io/component: validatingadmissionpolicy
    app.kubernetes.io/created-by: msi-acrpull
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
spec:
  policyName: "msi-acrpull-controller-token-request-policy"
  validationActions: [Deny]
  paramRef:
    name: "msi-acrpull-admission-policies-controller-config"
    namespace: "msi-acrpull-system"
    parameterNotFoundAction: "Deny"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "controller-secret-mutation-policy-binding"
  labels:
    app.kubernetes.io/component: validatingadmissionpolicy
    app.kubernetes.io/created-by: msi-acrpull
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
spec:
  policyName: "msi-acrpull-controller-secret-mutation-policy"
  validationActions: [Deny]
  paramRef:
    name: "msi-acrpull-admission-policies-controller-config"
    namespace: "msi-acrpull-system"
    parameterNotFoundAction: "Deny"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "controller-service-account-mutation-policy-binding"
  labels:
    app.kubernetes.io/component: validatingadmissionpolicy
    app.kubernetes.io/created-by: msi-acrpull
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
spec:
  policyName: "msi-acrpull-controller-service-account-mutation-policy"
  validationActions: [Deny]
  paramRef:
    name: "msi-acrpull-admission-policies-controller-config"
    namespace: "msi-acrpull-system"
    parameterNotFoundAction: "Deny"
---