# This is the configuration file for the MSI-ACRPull Controller. These values will be passed to the helm chart.
# The config map is an easy way to provide an example of the configuration.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the token audience: any opaque string, which the reconciler will be restricted to use
apiVersion: v1
kind: ConfigMap
metadata:
  name: "admission-policies-controller-config"
  labels:
    app.kubernetes.io/component: validatingadmissionpolicy
    app.kubernetes.io/created-by: msi-acrpull
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
data:
  controllerName: 'msi-acrpull-controller-manager'
  controllerNamespace: 'msi-acrpull-system'
  tokenAudience: 'api://AzureCRTokenExchange'