
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-msi-acrpull-microsoft-com-v1beta1-acrpullbinding
  failurePolicy: Fail
  name: vacrpullbinding.kb.io
  rules:
  - apiGroups:
    - msi-acrpull.microsoft.com
    apiVersions:
    - v1beta1
    operations:
    - UPDATE
    resources:
    - acrpullbindings
