# permissions for end users to view acrpullbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: acrpullbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msi-acrpull
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
  name: acrpullbinding-viewer-role
rules:
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings/status
  verbs:
  - get
