# permissions to do edit acrpullbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acrpullbinding-editor-role
rules:
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings/status
  verbs:
  - get
  - patch
  - update
