# permissions to do viewer acrpullbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acrpullbinding-viewer-role
rules:
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings/status
  verbs:
  - get
