apiVersion: msi-acrpull.microsoft.com/v1beta1
kind: AcrPullBinding
metadata:
  labels:
    app.kubernetes.io/name: acrpullbinding
    app.kubernetes.io/instance: acrpullbinding-sample
    app.kubernetes.io/part-of: msi-acrpull
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: msi-acrpull
  name: acrpullbinding-sample
spec:
  managedIdentityResourceID: "test-resource-id"
  acrServer: "test.azurecr.io"
