{{- if .Values.armAuth -}}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: msi-acrpull
  namespace: {{ .Release.Namespace }}
spec: 
  azureIdentity: msi-acrpull
  selector: {{ .Release.Name }}
{{- end}}