{{- if .Values.serviceAccount.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: msi-acrpull-leader-election-role
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    control-plane: controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msi-acrpull-manager-role
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - msi-acrpull.microsoft.com
  resources:
  - acrpullbindings/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msi-acrpull-proxy-role
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: msi-acrpull-metrics-reader
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: msi-acrpull-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: msi-acrpull-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: msi-acrpull-manager-rolebinding
  labels:
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: msi-acrpull-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: msi-acrpull-proxy-rolebinding
  labels:
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: msi-acrpull-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}