// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/authorizer/interfaces.go

// Package mock_authorizer is a generated GoMock package.
package mock_authorizer

import (
	context "context"
	reflect "reflect"

	azcore "github.com/Azure/azure-sdk-for-go/sdk/azcore"
	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// AcquireACRAccessToken mocks base method.
func (m *MockInterface) AcquireACRAccessToken(ctx context.Context, identityResourceID, clientID, acrFQDN, scope string) (azcore.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireACRAccessToken", ctx, identityResourceID, clientID, acrFQDN, scope)
	ret0, _ := ret[0].(azcore.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireACRAccessToken indicates an expected call of AcquireACRAccessToken.
func (mr *MockInterfaceMockRecorder) AcquireACRAccessToken(ctx, identityResourceID, clientID, acrFQDN, scope interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireACRAccessToken", reflect.TypeOf((*MockInterface)(nil).AcquireACRAccessToken), ctx, identityResourceID, clientID, acrFQDN, scope)
}
