apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: msi-acrpull-leader-election-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: msi-acrpull-leader-election-rolebinding
  namespace: msi-acrpull-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: msi-acrpull-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: msi-acrpull-system
