apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: acrpull
    app.kubernetes.io/managed-by: Helm
  name: acrpull-monitor
  namespace: {{ .Values.namespace }}
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: acrpull