# This is the configuration file for the MSI-ACRPull Controller. These values will be passed to the helm chart.
# The config map is an easy way to provide an example of the configuration.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the token audience: any opaque string, which the reconciler will be restricted to use
apiVersion: v1
kind: ConfigMap
metadata:
  name: "admission-policies-controller-config"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: acrpull
    app.kubernetes.io/managed-by: Helm
data:
  controllerServiceAccountName: 'acrpull'
  controllerNamespace: '{{ .Values.namespace }}'
  tokenAudience: 'api://AzureCRTokenExchange'