name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMG: acrpulltest.azurecr.io/msi-acrpull:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make docker-build

    - name: Azure Container Registry Login
      run: |
        az login --identity
        az acr login -n acrpulltest.azurecr.io

    - name: Push to CI ACR
      if: github.event_name == 'push'
      run: make docker-push
