name: Azure Workload Identity E2E

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  msi_acrpull_e2e:
    env:
      AZURE_CLIENT_ID: ecf12de5-b661-4194-8c94-3710b7d5472f
      AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
      AZURE_SUBSCRIPTION_ID: 0cc1cafa-578f-4fa5-8d6b-ddfd8d82e6ea
      UNIQUE_INPUT: '${{ github.base_ref }}-${{ github.head_ref }}-${{ github.job }}-${{ github.run_id }}'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.23.2"
          check-latest: true
      - name: Azure CLI
        run: |
          echo "Azure CLI Current installed version"
          az version
      - uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      - name: E2E test
        run: make -C test/ test "UNIQUE_INPUT=${UNIQUE_INPUT}"
      - name: Cleanup
        if: ${{ always() }}
        run: make -C test/ cleanup "UNIQUE_INPUT=${UNIQUE_INPUT}"