name: Image Vulnerabilities Scan

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  scan:
    name: Check image vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image
        env:
          IMG: "msi-acrpull:${{ github.sha }}"
        run: make docker-build

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "msi-acrpull:${{ github.sha }}"
          format: "table"
